export const PRODUCTIVITY_RULES = {
  ContentCreator: {
    productive_keywords: [
      "tutorial",
      "editing",
      "how to",
      "design",
      "marketing",
      "content",
      "camera",
      "video",
      "premiere",
      "photoshop",
      "capcut",
      "canva",
      "cut",
      "cap-cut",
    ],
    distracting_keywords: [
      "funny",
      "meme",
      "prank",
      "compilation",
      "reaction",
      "gaming highlights",
      "cat compilation",
      "fail compilation",
    ],
  },

  Student: {
    productive_keywords: [
      "lecture",
      "assignment",
      "tutorial",
      "research",
      "course",
      "exam",
      "notes",
      "study",
      "revision",
      "problem set",
    ],
    distracting_keywords: [
      "movie",
      "trailer",
      "celebrity",
      "gossip",
      "funny",
      "reaction",
      "drama",
    ],
  },

  SoftwareDeveloper: {
    productive_keywords: [
      "tutorial",
      "coding",
      "programming",
      "react",
      "python",
      "javascript",
      "typescript",
      "github",
      "stack overflow",
      "debug",
      "api",
      "backend",
      "frontend",
      "deploy",
      "devops",
      "database",
      "sql",
      "algorithm",
      "performance",
      "refactor",
    ],
    distracting_keywords: [
      "funny",
      "meme",
      "prank",
      "compilation",
      "reaction",
      "gaming",
    ],
  },

  Entrepreneur: {
    productive_keywords: [
      "pitch",
      "investor",
      "business",
      "finance",
      "marketing",
      "strategy",
      "roadmap",
      "sales",
      "branding",
      "negotiation",
      "product update",
    ],
    distracting_keywords: [
      "celebrity",
      "gossip",
      "trailer",
      "funny",
      "meme",
      "reaction",
    ],
  },
};

